const Property = require("../models/propertyModel");

// @desc    Create a new property listing
// @route   POST /api/properties
// @access  Private (Owners/Admins)
const createProperty = async (req, res) => {
  try {
    // Only allow owners or admins to post properties
    if (req.user.role !== "owner" && req.user.role !== "admin") {
      return res
        .status(403)
        .json({ message: "Only owners can create listings" });
    }

    const { title, propertyCategory, address, generalAmenities } = req.body;

    // Extract image URLs generated by Cloudinary
    const imageUrls = req.files ? req.files.map((file) => file.path) : [];

    if (imageUrls.length === 0) {
      return res
        .status(400)
        .json({ message: "At least one property image is required" });
    }

    // Parse stringified JSON from FormData
    const parsedAddress =
      typeof address === "string" ? JSON.parse(address) : address;
    const parsedAmenities =
      typeof generalAmenities === "string"
        ? JSON.parse(generalAmenities)
        : generalAmenities;

    // Build the base property object
    const propertyData = {
      ownerId: req.user._id, // Comes from the authMiddleware
      title,
      propertyCategory,
      address: parsedAddress,
      location: {
        type: "Point",
        coordinates: [73.8567, 18.5204], // Default to Pune coords for MVP if not provided by Mapbox
      },
      images: imageUrls,
      generalAmenities: parsedAmenities,
      status: "Pending", // Requires Admin approval
    };

    // Handle Dynamic Logic: Flat vs PG
    if (propertyCategory === "Flat") {
      propertyData.flatDetails =
        typeof req.body.flatDetails === "string"
          ? JSON.parse(req.body.flatDetails)
          : req.body.flatDetails;
    } else if (propertyCategory === "PG") {
      propertyData.roomConfigurations =
        typeof req.body.roomConfigurations === "string"
          ? JSON.parse(req.body.roomConfigurations)
          : req.body.roomConfigurations;
    }

    const newProperty = await Property.create(propertyData);
    res.status(201).json(newProperty);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Get all APPROVED properties with Pagination & Filtering
// @route   GET /api/properties?page=1&limit=20&city=Pune&category=PG&maxPrice=15000
// @access  Public
const getProperties = async (req, res) => {
  try {
    const { page, limit, city, category, maxPrice } = req.query;

    // Pagination defaults
    const pageNum = parseInt(page, 10) || 1;
    const limitNum = parseInt(limit, 10) || 20;
    const startIndex = (pageNum - 1) * limitNum;

    // 1. Base Query
    const query = { status: "Approved" };

    // 2. Dynamic Filters
    // If frontend sends ?city=Pune, add it to the query (case-insensitive)
    if (city) {
      query["address.city"] = new RegExp(city, "i");
    }

    // If frontend sends ?category=PG
    if (category) {
      query.propertyCategory = category;
    }

    // If frontend sends ?maxPrice=15000
    if (maxPrice) {
      // Because a Flat uses 'rentAmount' but a PG uses 'pricePerBed',
      // we tell MongoDB to find properties where EITHER of those is less than or equal to ($lte) the maxPrice.
      query.$or = [
        { "flatDetails.rentAmount": { $lte: Number(maxPrice) } },
        { "roomConfigurations.pricePerBed": { $lte: Number(maxPrice) } },
      ];
    }

    // 3. Count documents based on the FILTERS (not the whole database)
    const totalProperties = await Property.countDocuments(query);

    // 4. Fetch the filtered data
    const properties = await Property.find(query)
      .populate("ownerId", "name phone instagramId")
      .sort("-createdAt")
      .skip(startIndex)
      .limit(limitNum);

    res.status(200).json({
      success: true,
      count: properties.length,
      pagination: {
        currentPage: pageNum,
        totalPages: Math.ceil(totalProperties / limitNum),
        totalProperties,
      },
      data: properties,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Get properties owned by the logged-in user (For Owner Dashboard)
// @route   GET /api/properties/my-properties
// @access  Private (Owner)
const getMyProperties = async (req, res) => {
  try {
    const properties = await Property.find({ ownerId: req.user._id });
    res.status(200).json(properties);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Delete a property
// @route   DELETE /api/properties/:id
// @access  Private (Owner)
const deleteProperty = async (req, res) => {
  try {
    const property = await Property.findById(req.params.id);

    if (!property)
      return res.status(404).json({ message: "Property not found" });

    // Ensure the person deleting it actually owns it
    if (property.ownerId.toString() !== req.user._id.toString()) {
      return res
        .status(401)
        .json({ message: "Not authorized to delete this property" });
    }

    await property.deleteOne();
    res.status(200).json({ message: "Property removed successfully" });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

module.exports = {
  createProperty,
  getProperties,
  getMyProperties,
  deleteProperty,
};
