const Property = require("../models/propertyModel");

// @desc    Create a new property listing
// @route   POST /api/properties
// @access  Private (Owners/Admins)
const createProperty = async (req, res) => {
  try {
    // Only allow owners or admins to post properties
    if (req.user.role !== "owner" && req.user.role !== "admin") {
      return res
        .status(403)
        .json({ message: "Only owners can create listings" });
    }

    const { title, propertyCategory, address, generalAmenities } = req.body;

    // Extract image URLs generated by Cloudinary
    const imageUrls = req.files ? req.files.map((file) => file.path) : [];

    if (imageUrls.length === 0) {
      return res
        .status(400)
        .json({ message: "At least one property image is required" });
    }

    // Parse stringified JSON from FormData
    const parsedAddress =
      typeof address === "string" ? JSON.parse(address) : address;
    const parsedAmenities =
      typeof generalAmenities === "string"
        ? JSON.parse(generalAmenities)
        : generalAmenities;

    // Build the base property object
    const propertyData = {
      ownerId: req.user._id, // Comes from the authMiddleware
      title,
      propertyCategory,
      address: parsedAddress,
      location: {
        type: "Point",
        coordinates: [73.8567, 18.5204], // Default to Pune coords for MVP if not provided by Mapbox
      },
      images: imageUrls,
      generalAmenities: parsedAmenities,
      status: "Pending", // Requires Admin approval
    };

    // Handle Dynamic Logic: Flat vs PG
    if (propertyCategory === "Flat") {
      propertyData.flatDetails =
        typeof req.body.flatDetails === "string"
          ? JSON.parse(req.body.flatDetails)
          : req.body.flatDetails;
    } else if (propertyCategory === "PG") {
      propertyData.roomConfigurations =
        typeof req.body.roomConfigurations === "string"
          ? JSON.parse(req.body.roomConfigurations)
          : req.body.roomConfigurations;
    }

    const newProperty = await Property.create(propertyData);
    res.status(201).json(newProperty);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Get all APPROVED properties with Pagination & Filtering
// @route   GET /api/properties?page=1&limit=20&city=Pune&category=PG&maxPrice=15000
// @access  Public
const getProperties = async (req, res) => {
  try {
    const { page, limit, city, category, maxPrice } = req.query;

    // Pagination defaults
    const pageNum = parseInt(page, 10) || 1;
    const limitNum = parseInt(limit, 10) || 20;
    const startIndex = (pageNum - 1) * limitNum;

    // 1. Base Query
    const query = { status: "Approved" };

    // 2. Dynamic Filters
    // If frontend sends ?city=Pune, add it to the query (case-insensitive)
    if (city) {
      query["address.city"] = new RegExp(city, "i");
    }

    // If frontend sends ?category=PG
    if (category) {
      query.propertyCategory = category;
    }

    // If frontend sends ?maxPrice=15000
    if (maxPrice) {
      // Because a Flat uses 'rentAmount' but a PG uses 'pricePerBed',
      // we tell MongoDB to find properties where EITHER of those is less than or equal to ($lte) the maxPrice.
      query.$or = [
        { "flatDetails.rentAmount": { $lte: Number(maxPrice) } },
        { "roomConfigurations.pricePerBed": { $lte: Number(maxPrice) } },
      ];
    }

    // 3. Count documents based on the FILTERS (not the whole database)
    const totalProperties = await Property.countDocuments(query);

    // 4. Fetch the filtered data
    const properties = await Property.find(query)
      .populate("ownerId", "name phone ")
      .sort("-createdAt")
      .skip(startIndex)
      .limit(limitNum);

    res.status(200).json({
      success: true,
      count: properties.length,
      pagination: {
        currentPage: pageNum,
        totalPages: Math.ceil(totalProperties / limitNum),
        totalProperties,
      },
      data: properties,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Get properties owned by the logged-in user (For Owner Dashboard)
// @route   GET /api/properties/my-properties
// @access  Private (Owner)
const getMyProperties = async (req, res) => {
  try {
    const properties = await Property.find({ ownerId: req.user._id });
    res.status(200).json(properties);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Delete a property
// @route   DELETE /api/properties/:id
// @access  Private (Owner)
const deleteProperty = async (req, res) => {
  try {
    const property = await Property.findById(req.params.id);

    if (!property)
      return res.status(404).json({ message: "Property not found" });

    // Ensure the person deleting it actually owns it
    if (property.ownerId.toString() !== req.user._id.toString()) {
      return res
        .status(401)
        .json({ message: "Not authorized to delete this property" });
    }

    await property.deleteOne();
    res.status(200).json({ message: "Property removed successfully" });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Get ALL properties for Admin Dashboard (Paginated & Filtered)
// @route   GET /api/properties/admin/all?page=1&limit=20&status=Pending
// @access  Private (Admin Only)
const getAdminProperties = async (req, res) => {
  try {
    const { page, limit, status, search } = req.query;

    // Pagination setup
    const pageNum = parseInt(page, 10) || 1;
    const limitNum = parseInt(limit, 10) || 20;
    const startIndex = (pageNum - 1) * limitNum;

    // Base query object
    let query = {};

    // If admin wants to see only 'Rejected', 'Approved', or 'Pending'
    if (status) {
      query.status = status;
    }

    // Optional: Let admin search by property title
    if (search) {
      query.title = new RegExp(search, "i");
    }

    // Count for pagination math
    const totalProperties = await Property.countDocuments(query);

    const properties = await Property.find(query)
      .populate("ownerId", "name phone email")
      .sort("-createdAt") // Newest first
      .skip(startIndex)
      .limit(limitNum);

    res.status(200).json({
      success: true,
      count: properties.length,
      pagination: {
        currentPage: pageNum,
        totalPages: Math.ceil(totalProperties / limitNum),
        totalProperties,
      },
      data: properties,
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Update any property's status
// @route   PUT /api/properties/admin/:id/status
// @access  Private (Admin Only)
const updatePropertyStatus = async (req, res) => {
  try {
    const { status } = req.body;
    const validStatuses = ["Pending", "Approved", "Rejected", "Hidden"];

    if (!validStatuses.includes(status)) {
      return res.status(400).json({
        message: `Status must be one of: ${validStatuses.join(", ")}`,
      });
    }

    const property = await Property.findById(req.params.id);

    if (!property) {
      return res.status(404).json({ message: "Property not found" });
    }

    property.status = status;
    await property.save();

    res.status(200).json({
      message: `Property status updated to ${status}`,
      property,
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Get single property by ID
// @route   GET /api/properties/:id
// @access  Public
const getPropertyById = async (req, res) => {
  try {
    const property = await Property.findById(req.params.id).populate(
      "ownerId",
      "name email phone",
    ); // Get owner details so users can contact them

    if (!property) {
      return res.status(404).json({ message: "Property not found" });
    }

    res.status(200).json(property);
  } catch (error) {
    res.status(500).json({ message: "Invalid Property ID or Server Error" });
  }
};

// @desc    Update a property
// @route   PUT /api/properties/:id
// @access  Private (Owner Only)
const updateProperty = async (req, res) => {
  try {
    let property = await Property.findById(req.params.id);
    if (!property)
      return res.status(404).json({ message: "Property not found" });

    // Security Check: Make sure the logged-in user actually owns this property
    if (property.ownerId.toString() !== req.user._id.toString()) {
      return res
        .status(401)
        .json({ message: "Not authorized to edit this property" });
    }

    // Update Text Fields
    property.title = req.body.title || property.title;
    property.propertyCategory =
      req.body.propertyCategory || property.propertyCategory;

    if (req.body.address) property.address = JSON.parse(req.body.address);
    if (req.body.location) property.location = JSON.parse(req.body.location);
    if (req.body.generalAmenities)
      property.generalAmenities = JSON.parse(req.body.generalAmenities);

    if (req.body.flatDetails)
      property.flatDetails = JSON.parse(req.body.flatDetails);
    if (req.body.roomConfigurations)
      property.roomConfigurations = JSON.parse(req.body.roomConfigurations);

    // If new images were uploaded, process them via Cloudinary/Multer and append to existing
    if (req.files && req.files.length > 0) {
      const newImagePaths = req.files.map((file) => file.path);
      property.images = [...property.images, ...newImagePaths];
    }

    // Every time an owner edits a property, it should probably go back to 'Pending' for admin review
    property.status = "Pending";

    const updatedProperty = await property.save();
    res.status(200).json(updatedProperty);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Get latest approved properties for the homepage carousel
// @route   GET /api/properties/latest
// @access  Public
const getLatestProperties = async (req, res) => {
  try {
    const properties = await Property.find({ status: "Approved" })
      .sort({ createdAt: -1 }) // -1 means newest first
      .limit(6); // Perfect amount for a UI carousel

    res.status(200).json(properties);
  } catch (error) {
    res.status(500).json({ message: "Failed to fetch latest properties" });
  }
};

// Make sure to export it at the bottom!

module.exports = {
  createProperty,
  getProperties,
  getMyProperties,
  getLatestProperties,
  deleteProperty,
  getAdminProperties,
  getPropertyById,
  updatePropertyStatus,
  updateProperty,
};
